# Configuration du thème
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Configuration du site
locale: "fr-FR"
title: "Votre Blog Santé"
subtitle: "Nutrition, Fitness & Bien-être"
name: "Votre Nom"
description: "Guide complet pour une vie saine et équilibrée"
url: "https://mart95dev.github.io/cetovitality2/"
repository: "mart95dev/cetovitality2"

# Configuration des plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Configuration de l'auteur
author:
  name: "Votre Nom"
  avatar: "/assets/images/bio-photo.jpg" # Ajoutez une photo de profil
  bio: "Votre biographie courte."
  location: "Votre Ville"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:votre@email.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/votre-profil"

# Configuration par défaut pour les posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "categories"

# Inclure les pages
include: ["_pages"]

# Configuration par défaut pour les pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Configuration de la pagination
paginate: 10
paginate_path: "/page/:num/"

# Configuration Disqus (pour les commentaires)
disqus:
  shortname: votre-shortname-disqus

# Configuration des images par défaut
defaults:
  - scope:
      path: ""
      type: posts
    values:
      image: /assets/images/default-post.jpg

# Ajoutez ces lignes à votre configuration
social_links:
  twitter: votre-compte-twitter
  facebook: votre-compte-facebook
  github: votre-compte-github

# Catégories principales
category_archive:
  type: liquid
  path: /categories/

# Configuration des catégories par défaut
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: "categories"

# Navigation latérale des catégories
categories:
  - nutrition:
    - keto
    - mediterraneen
    - vegetarien
  - fitness:
    - musculation
    - cardio
    - yoga
  - bien-etre:
    - meditation
    - sommeil
    - stress
  - recettes:
    - keto
    - low-carb
    - vegan
  - developpement-personnel:
    - motivation
    - habitudes
    - productivite
  - biohacking:
    - supplements
    - technologie
    - optimisation
